version: 2.1
orbs:
  nais: 'navikt/nais-deployment@1.4.1'
jobs:
  build_and_release:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run: mvn clean install
      - persist_to_workspace:
          root: .
          paths:
            - target/app.jar
            - Dockerfile
      - attach_workspace:
          at: ~/project
      - nais/docker-deploy:
          image: navikt/peproxy
workflows:
  version: 2
  deploy-docker-and-nais:
    jobs:
      - build_and_release:
          context: NAIS deployment
          filters:
            branches:
              only:
                - master
      - nais/deploy:
          repo: navikt/peproxy
          image: navikt/peproxy
          github-app-id: 23087
          nais-template: nais.yaml
          environment: dev-fss
          team: teampeon
          requires:
            - build_and_release
          filters:
            branches:
              only:
                - master